### ISSUE TITLE
Rules for RNAMMER, TmHMM and SignalP 

### ISSUE THREAD

**Issue by mictadlo** [jlanga/smsk_trinotate#1]
Hi, could please send me the rules for RNAMMER, TmHMM and SignalP and I will register and install the tools by myself?

Thank you in advance.

Michal

**Comment by jlanga** [comment]
Hi @mictadlo .

Thanks for your interest. I'll push a commit with those lines commented. If I'm not wrong, the changes only apply to `src/snakefiles/trinotate.py`. Three additional rules and change the rule that dumps the results into the database.

I can't say when.

Cheers,

Jorge

**Comment by jlanga** [comment]
Done. Uncomment blocks from `src/snakefiles/trinotate.py` and write your path to rnammer in `src/config.yaml`.

Tell me if you are able to run it.
