### ISSUE TITLE
MissingInputException

### ISSUE THREAD

**Issue by mictadlo** [jlanga/smsk_trinotate#10]
Hi,
I have got the following error:
```
snakemake
Building DAG of jobs...
MissingInputException in line 346 of /smsk_trinotate/src/snakefiles/trinotate.py:
Missing input files for rule trinotate_load:
results/trinotate/rnammer.gff
```

What did I miss?

Thank you in advance

Michal

**Comment by jlanga** [comment]
#5 maybe?

**Comment by mictadlo** [comment]
Hi,
It did not even produced any output files. By any chance, do you know where should I search for problems?

Best wishes,

Michal

**Comment by jlanga** [comment]
Hi, Mic.

Can you try executing the pipeline in the `optional_programs` branch?

I think it is about `rnammer` not finding rRNA transcripts. I've added one that should make it work.

Jorge

**Comment by mictadlo** [comment]
Hi, I did `wget -c https://raw.githubusercontent.com/jlanga/smsk_trinotate/optional_programs/transcript.fa` but I still get the same error.
