### ISSUE TITLE
empty file handling

### ISSUE THREAD

**Issue by mictadlo** [jlanga/smsk_trinotate#6]
Hi,
I noticed that in my case TMHMM and blast chunks produced empty files which caused the stopping of snakemake.

Any idea how to handle this problem?

Thank you in advance.

Michal

**Comment by jlanga** [comment]
Hi. It should be enough with a touch(filename) as output variable.

Anyway, I think that snakemake allows empty files as a valid output, but will complain if it doesn't exist.
